language: node_js

node_js:
  - 13.13.0

cache: yarn

install: 
  - yarn install

script: 
  - git config user.name "bbcfive"
  - git config user.email "bbcfive@163.com"
  - yarn run build
  - yarn run clean
  - yarn run deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  on: 
    branch: master