language: node_js

node_js:
  - 8

cache: yarn

install: 
  - yarn install

script: 
  - yarn run build
  - yarn run deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  on: 
    branch: master